import authRouter from "./auth";
import roleRouter from "./role";
import postRouter from "./post/post";
import tagRouter from "./tag";
import postTagRouter from "./post/post-tag";
import supportRouter from "./support";
import statusActivityRouter from "./status-activity";
import userRouter from "./user";
import friendRouter from "./friend";
import documentShareRouter from "./document/document-share";
import cmtDocumentRouter from "./document/cmt-document";
import commentRouter from "./post/comment";
import reactionRouter from "./post/reaction";
import conversationRouter from "./conversation";
import markPostRouter from "./post/mark-post";
import mediaRouter from "./media";
import messagerRouter from "./messager";
import nationRouter from "./nation";
import userNotificationRouter from "./user-noti";
import pageRouter from "./page/page";
import pageMemberRouter from "./page/page-member";
import pageOpenHourRouter from "./page/page-open-hours";
import storyRouter from "./story";
import userSocialRouter from "./user-social";
import statusActionRouter from "./status-action";
import noticeTypeRouter from "./notice-type";
import groupRouter from "./group/group";
import groupMemberRouter from "./group/group-member";
import groupInvitationRouter from "./group/group-invitation";
import groupRequestRouter from "./group/group-request";
import eventRouter from "./event/event";
import eventMemberRouter from "./event/event-member";
import eventInvitationRouter from "./event/event-invitation";
import eventRequestRouter from "./event/event-request";
import notificationRouter from "./notification/notification";
import notificationCreatedRouter from "./notification/notification-created";
import notificationSettingRouter from "./notification/notification-setting";
import userNotificationsNewRouter from "./notification/user-notification";

const initRoutes = (app) => {
  app.use("/api/v1/auth", authRouter);
  app.use("/api/v1/roles", roleRouter);
  app.use("/api/v1/posts", postRouter);
  app.use("/api/v1/tags", tagRouter);
  app.use("/api/v1/post-tags", postTagRouter);
  app.use("/api/v1/supports", supportRouter);
  app.use("/api/v1/status-activities", statusActivityRouter);
  app.use("/api/v1/users", userRouter);
  app.use("/api/v1/friends", friendRouter);
  app.use("/api/v1/document-shares", documentShareRouter);
  app.use("/api/v1/cmt-documents", cmtDocumentRouter);
  app.use("/api/v1/comments", commentRouter);
  app.use("/api/v1/reactions", reactionRouter);
  app.use("/api/v1/conversations", conversationRouter);
  app.use("/api/v1/mark-posts", markPostRouter);
  app.use("/api/v1/medias", mediaRouter);
  app.use("/api/v1/messagers", messagerRouter);
  app.use("/api/v1/nations", nationRouter);
  app.use("/api/v1/user-notifications", userNotificationRouter);
  app.use("/api/v1/pages", pageRouter);
  app.use("/api/v1/page-members", pageMemberRouter);
  app.use("/api/v1/page-open-hours", pageOpenHourRouter);
  app.use("/api/v1/stories", storyRouter);
  app.use("/api/v1/user-socials", userSocialRouter);
  app.use("/api/v1/status-actions", statusActionRouter);
  app.use("/api/v1/notice-types", noticeTypeRouter);
  app.use("/api/v1/groups", groupRouter);
  app.use("/api/v1/group-members", groupMemberRouter);
  app.use("/api/v1/group-invitations", groupInvitationRouter);
  app.use("/api/v1/group-requests", groupRequestRouter);
  app.use("/api/v1/events", eventRouter);
  app.use("/api/v1/event-members", eventMemberRouter);
  app.use("/api/v1/event-invitations", eventInvitationRouter);
  app.use("/api/v1/event-requests", eventRequestRouter);
  app.use("/api/v1/notifications", notificationRouter);
  app.use("/api/v1/notification-creators", notificationCreatedRouter);
  app.use("/api/v1/notification-settings", notificationSettingRouter);
  app.use("/api/v1/user-notifications-new", userNotificationsNewRouter);

  return app.use("/", (req, res) => {
    res.send("server on...");
  });
};

export default initRoutes;
