import authRouter from "./auth.js";
import roleRouter from "./role.js";
import postRouter from "./post/post.js";
import tagRouter from "./tag.js";
import postTagRouter from "./post/post-tag.js";
import supportRouter from "./support.js";
import statusActivityRouter from "./status-activity.js";
import userRouter from "./user.js";
import friendRouter from "./friend.js";
import documentShareRouter from "./document/document-share.js";
import cmtDocumentRouter from "./document/cmt-document.js";
import commentRouter from "./post/comment.js";
import reactionRouter from "./post/reaction.js";
import conversationRouter from "./conversation.js";
import markPostRouter from "./post/mark-post.js";
import mediaRouter from "./media.js";
import messagerRouter from "./messager.js";
import nationRouter from "./nation.js";
import userNotificationRouter from "./user-noti.js";
import pageRouter from "./page/page.js";
import pageMemberRouter from "./page/page-member.js";
import pageOpenHourRouter from "./page/page-open-hours.js";
import storyRouter from "./story.js";
import userSocialRouter from "./user-social.js";
import statusActionRouter from "./status-action.js";
import noticeTypeRouter from "./notice-type.js";
import groupRouter from "./group/group.js";
import groupMemberRouter from "./group/group-member.js";
import groupInvitationRouter from "./group/group-invitation.js";
import groupRequestRouter from "./group/group-request.js";
import eventRouter from "./event/event.js";
import eventMemberRouter from "./event/event-member.js";
import eventInvitationRouter from "./event/event-invitation.js";
import eventRequestRouter from "./event/event-request.js";
import notificationRouter from "./notification/notification.js";
import notificationCreatedRouter from "./notification/notification-created.js";
import notificationSettingRouter from "./notification/notification-setting.js";
import postFriend from "./post/post-friend.js";
import postMedia from "./post/post-media.js";
import participantRouter from "./conversation-participant.js";
import searchRouter from "./search.js";
import statisticRouter from "./statistics.routes.js"

const initRoutes = (app) => {
  app.use("/api/v1/auth", authRouter);
  app.use("/api/v1/roles", roleRouter);
  app.use("/api/v1/posts", postRouter);
  app.use("/api/v1/tags", tagRouter);
  app.use("/api/v1/post-tags", postTagRouter);
  app.use("/api/v1/supports", supportRouter);
  app.use("/api/v1/status-activities", statusActivityRouter);
  app.use("/api/v1/users", userRouter);
  app.use("/api/v1/friends", friendRouter);
  app.use("/api/v1/document-shares", documentShareRouter);
  app.use("/api/v1/cmt-documents", cmtDocumentRouter);
  app.use("/api/v1/comments", commentRouter);
  app.use("/api/v1/reactions", reactionRouter);
  app.use("/api/v1/conversations", conversationRouter);
  app.use("/api/v1/mark-posts", markPostRouter);
  app.use("/api/v1/medias", mediaRouter);
  app.use("/api/v1/messagers", messagerRouter);
  app.use("/api/v1/nations", nationRouter);
  app.use("/api/v1/user-notifications", userNotificationRouter);
  app.use("/api/v1/pages", pageRouter);
  app.use("/api/v1/page-members", pageMemberRouter);
  app.use("/api/v1/page-open-hours", pageOpenHourRouter);
  app.use("/api/v1/stories", storyRouter);
  app.use("/api/v1/user-socials", userSocialRouter);
  app.use("/api/v1/status-actions", statusActionRouter);
  app.use("/api/v1/notice-types", noticeTypeRouter);
  app.use("/api/v1/groups", groupRouter);
  app.use("/api/v1/group-members", groupMemberRouter);
  app.use("/api/v1/group-invitations", groupInvitationRouter);
  app.use("/api/v1/group-requests", groupRequestRouter);
  app.use("/api/v1/events", eventRouter);
  app.use("/api/v1/event-members", eventMemberRouter);
  app.use("/api/v1/event-invitations", eventInvitationRouter);
  app.use("/api/v1/event-requests", eventRequestRouter);
  app.use("/api/v1/notifications", notificationRouter);
  app.use("/api/v1/notification-creators", notificationCreatedRouter);
  app.use("/api/v1/notification-settings", notificationSettingRouter);
  app.use("/api/v1/post-medias", postMedia);
  app.use("/api/v1/post-friends", postFriend);
  app.use("/api/v1/participants", participantRouter);
  app.use("/api/v1/search", searchRouter);
  app.use("/api/v1/statistics", statisticRouter);

  return app.use("/", (req, res) => {
    res.send("server on...");
  });
};

export default initRoutes;
