const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_REQUEST: 'LOGIN_REQUEST',

    PROFILE_REQUEST: 'PROFILE_REQUEST',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILURE: 'PROFILE_FAILURE',
    USER_SOCIAL_REQUEST: 'USER_SOCIAL_REQUEST',
    USER_SOCIAL_SUCCESS: 'USER_SOCIAL_SUCCESS',
    USER_SOCIAL_FAILURE: 'USER_SOCIAL_FAILURE'
}

export default actionTypes