const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',

    PROFILE_REQUEST: 'PROFILE_REQUEST',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILURE: 'PROFILE_FAILURE',
    USER_SOCIAL_REQUEST: 'USER_SOCIAL_REQUEST',
    USER_SOCIAL_SUCCESS: 'USER_SOCIAL_SUCCESS',
    USER_SOCIAL_FAILURE: 'USER_SOCIAL_FAILURE',

    FRIEND_ACCEPTED_REQUEST: 'FRIEND_ACCEPTED_REQUEST',
    FRIEND_ACCEPTED_SUCCESS: 'FRIEND_ACCEPTED_SUCCESS',
    FRIEND_ACCEPTED_FAILURE: 'FRIEND_ACCEPTED_FAILURE',
    FRIEND_BY_DATE_REQUEST: 'FRIEND_BY_DATE_REQUEST',
    FRIEND_BY_DATE_SUCCESS: 'FRIEND_BY_DATE_SUCCESS',
    FRIEND_BY_DATE_FAILURE: 'FRIEND_BY_DATE_FAILURE',
    FRIEND_PENDING_REQUEST: 'FRIEND_PENDING_REQUEST',
    FRIEND_PENDING_SUCCESS: 'FRIEND_PENDING_SUCCESS',
    FRIEND_PENDING_FAILURE: 'FRIEND_PENDING_FAILURE',
    FRIEND_SENT_REQUEST: 'FRIEND_SENT_REQUEST',
    FRIEND_SENT_SUCCESS: 'FRIEND_SENT_SUCCESS',
    FRIEND_SENT_FAILURE: 'FRIEND_SENT_FAILURE',

    CONFIRM_FRIEND_SUCCESS: 'CONFIRM_FRIEND_SUCCESS',
    CONFIRM_FRIEND_FAILURE: 'CONFIRM_FRIEND_FAILURE',
    REJECTED_FRIEND_SUCCESS: 'REJECTED_FRIEND_SUCCESS',
    REJECTED_FRIEND_FAILURE: 'REJECTED_FRIEND_FAILURE',

    GROUP_SUCCESS: 'GROUP_SUCCESS',
    GROUP_FAILURE: 'GROUP_FAILURE',
    GROUP_MEMBERS_SUCCESS: 'GROUP_MEMBERS_SUCCESS',
    GROUP_MEMBERS_FAILURE: 'GROUP_MEMBERS_FAILURE',
    MY_GROUP_SUCCESS: 'MY_GROUP_SUCCESS',
    MY_GROUP_FAILURE: 'MY_GROUP_FAILURE',
    GROUP_FIND_ONE_SUCCESS: 'GROUP_FIND_ONE_SUCCESS',
    GROUP_FIND_ONE_FAILURE: 'GROUP_FIND_ONE_FAILURE',

    GROUP_POST_SUCCESS: 'GROUP_POST_SUCCESS',
    GROUP_POST_FAILURE: 'GROUP_POST_FAILURE',

    POST_MEDIA_SUCCESS: 'POST_MEDIA_SUCCESS',
    POST_MEDIA_FAILURE: 'POST_MEDIA_FAILURE',
    POST_TAG_SUCCESS: 'POST_TAG_SUCCESS',
    POST_TAG_FAILURE: 'POST_TAG_FAILURE',

    CONVERSATION_SUCCESS: 'CONVERSATION_SUCCESS',
    CONVERSATION_FAILURE: 'CONVERSATION_FAILURE',

    PARICIPANT_SUCCESS: 'PARICIPANT_SUCCESS',
    PARICIPANT_FAILURE: 'PARICIPANT_FAILURE',

    TAG_SUCCESS: 'TAG_SUCCESS',
    TAG_FAILURE: 'TAG_FAILURE',

    SUPPORT_SUCCESS: 'SUPPORT_SUCCESS',
    SUPPORT_FAILURE: 'SUPPORT_FAILURE',

    NATION_SUCCESS: 'NATION_SUCCESS',
    NATION_FAILURE: 'NATION_FAILURE',

    REPORT_SUCCESS: 'REPORT_SUCCESS',
    REPORT_FAILURE: 'REPORT_FAILURE',

    STATUS_ACTIVITY_SUCCESS: 'STATUS_ACTIVITY_SUCCESS',
    STATUS_ACTIVITY_FAILURE: 'STATUS_ACTIVITY_FAILURE',

}

export default actionTypes