const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_REQUEST: 'LOGIN_REQUEST',

    PROFILE_REQUEST: 'PROFILE_REQUEST',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILURE: 'PROFILE_FAILURE',
    USER_SOCIAL_REQUEST: 'USER_SOCIAL_REQUEST',
    USER_SOCIAL_SUCCESS: 'USER_SOCIAL_SUCCESS',
    USER_SOCIAL_FAILURE: 'USER_SOCIAL_FAILURE',

    FRIEND_ACCEPTED_REQUEST: 'FRIEND_ACCEPTED_REQUEST',
    FRIEND_ACCEPTED_SUCCESS: 'FRIEND_ACCEPTED_SUCCESS',
    FRIEND_ACCEPTED_FAILURE: 'FRIEND_ACCEPTED_FAILURE',
    FRIEND_BY_DATE_REQUEST: 'FRIEND_BY_DATE_REQUEST',
    FRIEND_BY_DATE_SUCCESS: 'FRIEND_BY_DATE_SUCCESS',
    FRIEND_BY_DATE_FAILURE: 'FRIEND_BY_DATE_FAILURE',
    FRIEND_PENDING_REQUEST: 'FRIEND_PENDING_REQUEST',
    FRIEND_PENDING_SUCCESS: 'FRIEND_PENDING_SUCCESS',
    FRIEND_PENDING_FAILURE: 'FRIEND_PENDING_FAILURE',
    FRIEND_SENT_REQUEST: 'FRIEND_SENT_REQUEST',
    FRIEND_SENT_SUCCESS: 'FRIEND_SENT_SUCCESS',
    FRIEND_SENT_FAILURE: 'FRIEND_SENT_FAILURE',

    CONFIRM_FRIEND_SUCCESS: 'CONFIRM_FRIEND_SUCCESS',
    CONFIRM_FRIEND_FAILURE: 'CONFIRM_FRIEND_FAILURE',
    REJECTED_FRIEND_SUCCESS: 'REJECTED_FRIEND_SUCCESS',
    REJECTED_FRIEND_FAILURE: 'REJECTED_FRIEND_FAILURE',

    GROUP_SUCCESS: 'GROUP_SUCCESS',
    GROUP_FAILURE: 'GROUP_FAILURE',
    GROUP_MEMBERS_SUCCESS: 'GROUP_MEMBERS_SUCCESS',
    GROUP_MEMBERS_FAILURE: 'GROUP_MEMBERS_FAILURE',

}

export default actionTypes